# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Exit Zer0 Design
email: jason.c.willey@gmail.com
description: > # Website for Exit Zer0 Design and Jason C. Willey
  baseurl: /blog
url: "http://www.ExitZer0Designs.com" 

# Social media profiles - feel free to add more here
twitter_username: ExitZer0Designs
github_username:  jasoncwilley
facebook_username: ExitZer0Designs
#instagram_username: ExitZer0Designs
#googleplus_username: jason.c.willey@gmail.com



# Address information
address_street: 969 Piedmont Avenue
address_city: Oakland
address_state: CA
address_zip: 96010
